# Generated by Django 5.1.15 on 2026-07-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("icon_emoji", models.CharField(default="🏆", max_length=10)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=True, help_text="Show as wide featured card"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ImpactStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "value",
                    models.CharField(
                        help_text="e.g. '3.76', '8+', '🏆 NASA'", max_length=100
                    ),
                ),
                (
                    "is_accent",
                    models.BooleanField(
                        default=False, help_text="Use accent colour for value"
                    ),
                ),
                (
                    "data_count",
                    models.CharField(
                        blank=True,
                        help_text="Numeric target for count-up animation (leave blank for emoji values)",
                        max_length=50,
                    ),
                ),
                (
                    "is_decimal",
                    models.BooleanField(
                        default=False, help_text="Use decimal count-up (e.g. 3.76)"
                    ),
                ),
                (
                    "custom_font_size",
                    models.CharField(
                        blank=True,
                        help_text="Override font-size inline style (e.g. clamp(32px,5vw,48px))",
                        max_length=100,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Impact Stat",
                "verbose_name_plural": "Impact Stats",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LeadershipRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=300)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Show accent dot for current roles"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Leadership Role",
                "verbose_name_plural": "Leadership Roles",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Md. Mehedi Hasan", max_length=200)),
                (
                    "title",
                    models.CharField(
                        default="AI & ML Researcher · NASA International Space Apps Champion 2025 · IEEE Member",
                        max_length=300,
                    ),
                ),
                (
                    "tagline",
                    models.TextField(
                        default="Building interpretable machine learning systems at the intersection of behavioral modeling, social engineering detection, and socio-technical resilience."
                    ),
                ),
                (
                    "about_quote",
                    models.TextField(
                        default="I work at the intersection of AI, behavioral modeling, and socio-technical resilience building systems that are not only accurate but explainable and grounded in human reality."
                    ),
                ),
                (
                    "about_body_1",
                    models.TextField(
                        default="I'm a BSc Computer Science & Engineering student at Dhaka International University (CGPA 3.76 / 4.00), graduating December 2027. My research focuses on detecting social engineering through interpretable behavioral anomaly modeling, predicting system failures using socio-economic and IoT data, and building continual learning frameworks for dynamic environments."
                    ),
                ),
                (
                    "about_body_2",
                    models.TextField(
                        default="As President of DIU Computer Programming Club and an active IEEE & IEEE Computer Society Member, I combine research depth with community leadership championed by a NASA Space Apps 2025 victory with Team Polaris."
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="meetmehedi1@gmail.com", max_length=254),
                ),
                (
                    "linkedin_url",
                    models.URLField(default="https://www.linkedin.com/in/meetmehedi"),
                ),
                (
                    "github_url",
                    models.URLField(default="https://github.com/meetmehedi"),
                ),
                (
                    "orcid_url",
                    models.URLField(default="https://orcid.org/0009-0006-1427-8769"),
                ),
                (
                    "facebook_url",
                    models.URLField(default="https://www.facebook.com/meetmehedi1/"),
                ),
                (
                    "twitter_handle",
                    models.CharField(default="@meetmehedi", max_length=100),
                ),
                (
                    "canonical_url",
                    models.URLField(default="https://www.mdmehedihasan.us/"),
                ),
                ("cgpa", models.CharField(default="3.76", max_length=20)),
                ("papers_count", models.CharField(default="8+", max_length=20)),
                (
                    "edu_current_institution",
                    models.CharField(
                        default="Dhaka International University", max_length=200
                    ),
                ),
                (
                    "edu_degree",
                    models.CharField(
                        default="B.Sc. Computer Science & Engineering", max_length=200
                    ),
                ),
                (
                    "edu_period",
                    models.CharField(default="Sep 2023 – Dec 2027", max_length=100),
                ),
                (
                    "edu_hsc_institution",
                    models.CharField(
                        default="BAF Shaheen College Jashore", max_length=200
                    ),
                ),
                (
                    "edu_hsc_degree",
                    models.CharField(
                        default="Higher Secondary Certificate (HSC)", max_length=200
                    ),
                ),
                (
                    "edu_hsc_period",
                    models.CharField(default="Sep 2020 – Dec 2022", max_length=100),
                ),
                ("edu_hsc_gpa", models.CharField(default="4.75 / 5.00", max_length=20)),
                (
                    "research_tags",
                    models.TextField(
                        default="Behavioral ML,Social Engineering Detection,Interpretable AI,Socio-Economic Modeling,Continual Learning,Geospatial Risk,Computer Vision,LLMs & GenAI"
                    ),
                ),
                (
                    "availability_text",
                    models.CharField(
                        default="Open for Research Collaborations", max_length=200
                    ),
                ),
                (
                    "contact_headline",
                    models.CharField(default="Let's Shape the Future", max_length=200),
                ),
                (
                    "contact_sub",
                    models.TextField(
                        default="Open for research collaborations, engineering challenges, or just a friendly conversation about AI and its impact on humanity."
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                (
                    "icon_emoji",
                    models.CharField(
                        blank=True, help_text="e.g. 🌍 🤖 ⚡", max_length=10
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("nasa", "🏆 NASA Winner"),
                            ("research", "📖 Research"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "badge_label",
                    models.CharField(
                        blank=True, help_text="Override badge text", max_length=100
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags e.g. NASA API,Three.js,Machine Learning",
                        max_length=500,
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("normal", "Normal (1 col)"),
                            ("featured", "Featured (2 cols)"),
                            ("handbook", "Handbook (full width)"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                (
                    "authors",
                    models.TextField(
                        help_text="Use 'Hasan, M. M.' for self — will be bolded automatically"
                    ),
                ),
                ("venue", models.CharField(blank=True, max_length=300)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("review", "Under Review"),
                            ("ongoing", "Ongoing"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                (
                    "display_index",
                    models.CharField(
                        default="01",
                        help_text="Display label e.g. 01, R1, O1",
                        max_length=10,
                    ),
                ),
                (
                    "bibtex_key",
                    models.SlugField(
                        blank=True,
                        help_text="JavaScript key for BibTeX copy (e.g. hasan2025socio)",
                        max_length=100,
                    ),
                ),
                (
                    "bibtex_entry",
                    models.TextField(blank=True, help_text="Full BibTeX entry"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["status", "order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "is_highlighted",
                    models.BooleanField(default=False, help_text="Accent colour pill"),
                ),
                (
                    "row",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Row 1 (left → right)"),
                            (2, "Row 2 (right → left)"),
                        ],
                        default=1,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["row", "order"],
            },
        ),
    ]
